# Generated by Django 5.1.4 on 2026-08-23 06:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=64, unique=True)),
                ('last_contacted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('payment_degradation', 'Payment degradation'), ('subscription_failure', 'Subscription failure'), ('receivable', 'B2B receivable')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('customer_id', models.CharField(db_index=True, max_length=64)),
                ('customer_name', models.CharField(blank=True, max_length=128)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('merchant_id', models.CharField(default='demo_merchant', max_length=64)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('processing', 'Processing'), ('recovered', 'Recovered'), ('escalated', 'Escalated'), ('held', 'Held'), ('failed', 'Failed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id', 'created_at'], name='recovery_tr_custome_95eb7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuardrailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=64)),
                ('rule_result', models.CharField(choices=[('passed', 'Passed'), ('blocked', 'Blocked')], max_length=16)),
                ('detail', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardrail_events', to='recovery.transaction')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.CharField(max_length=128)),
                ('confidence', models.FloatField()),
                ('reasoning_text', models.TextField()),
                ('agent_run_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='recovery.transaction')),
            ],
            options={
                'ordering': ['-agent_run_at'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_action', models.CharField(choices=[('retry_order', 'Re-attempt same order'), ('new_payment_link', 'Issue fresh payment link'), ('registration_link', 'Send registration link'), ('invoice_reminder', 'Resend invoice reminder'), ('voice_reminder', 'Hinglish voice reminder'), ('escalate', 'Escalate to human queue'), ('hold', 'Hold — guardrail cooldown')], max_length=32)),
                ('reasoning_text', models.TextField()),
                ('guardrail_checks_passed', models.JSONField(default=list)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='recovery.transaction')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('actor', models.CharField(choices=[('agent', 'Agent'), ('system', 'System'), ('human', 'Human')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='recovery.transaction')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('retry', 'Retry'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('voice', 'Voice'), ('escalate', 'Escalate')], max_length=16)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('api_response', models.JSONField(default=dict)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('simulated', 'Simulated')], max_length=16)),
                ('amount_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='recovery.transaction')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('run_after', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_actions', to='recovery.transaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('transaction',), name='one_pending_scheduled_action_per_txn')],
            },
        ),
    ]
