# Generated by Django 5.1.4 on 2026-08-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0002_audit_log_append_only_trigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledaction',
            options={'ordering': ['-created_at']},
        ),
    ]
