# Generated by Django 5.1.4 on 2026-08-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0003_alter_scheduledaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
