# Generated by Django 5.1.4 on 2026-08-31 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0004_broadcastevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromiseToPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promised_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promise_date', models.DateField()),
                ('source', models.CharField(choices=[('voice', 'Voice'), ('manual', 'Manual')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('kept', 'Kept'), ('broken', 'Broken')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='recovery.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('transaction',), name='one_pending_promise_to_pay_per_txn')],
            },
        ),
    ]
