# Generated by Django 5.1.4 on 2026-08-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0005_promisetopay'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checkout_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_payment_method',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('payment_degradation', 'Payment degradation'), ('subscription_failure', 'Subscription failure'), ('receivable', 'B2B receivable'), ('checkout_dropoff', 'Checkout drop-off')], max_length=32),
        ),
    ]
