# Generated by Django 5.1.4 on 2026-08-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0006_transaction_checkout_initiated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
