# Generated by Django 5.1.4 on 2026-08-31 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0007_transaction_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandateSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('recovered', 'Recovered'), ('escalated', 'Escalated'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mandate_sequence', to='recovery.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
